rblog_html/rBlog/config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'about' => 'about#index'
  namespace :admin do
    get 'sessions/new'
    get 'sessions/create'
  end
  namespace :admin do
    get 'users/new'
    get 'users/edit'
    get 'users/update'
    get 'users/show'
    get 'users/create'
    get 'users/index'
    get 'users/destroy'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'

  resources :posts, :categories, :comments
  resources "contacts", only: [:new, :create]

  namespace :admin do
     resources :posts, :categories, :comments, :users
  end	  

  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rblog_html/rBlog/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts

	validates :name, presence: true

	def self.search(query)
		where("name like ?", "%#{query}%")
	end
end

rblog_html/rBlog/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

rblog_html/rBlog/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
	has_many :comments
	
	validates :title, presence: true
	validates :category_id, presence: true
	validates :body, presence: true

	has_attached_file :image, :default_url => ":style/rails1.jpg"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.search(query)
		where("title like ? OR body like ?", "%#{query}%", "%#{query}%")
	end
end

rblog_html/rBlog/app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	before_save :encrypt_password

	has_many :posts

	validates :name, presence: true
	validates :email, presence: true
	validates :password, presence: true
	validates :password, confirmation: true

	def self.authenticate(email, password)
    	user = find_by_email(email)
	    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
	      user
	    else
	      nil
	    end
  	end
  
  	def encrypt_password
	    if password.present?
	      self.password_salt = BCrypt::Engine.generate_salt
	      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	    end
  	end

  	def self.search(query)
		where("name like ? OR email like ?", "%#{query}%", "%#{query}%")
	end
end

rblog_html/rBlog/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

rblog_html/rBlog/app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  def destroy
  end
end

rblog_html/rBlog/app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::ApplicationController
  def new
    @page_title = 'Add Post'
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if params[:post][:image].blank?
      @post.image = nil
    end

    if @post.save
      flash[:notice] = 'Post Created'
      redirect_to admin_posts_path
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if params[:post][:image].blank?
      @post.image = nil
    end

    if @post.update(post_params)
      flash[:notice] = 'Post Updated'

      redirect_to admin_posts_path
    else
      render 'new'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    flash[:notice] = 'Post Removed'

      redirect_to admin_posts_path
  end

  def index
    if params[:search]
      @posts = Post.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @posts = Post.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :category_id, :user_id, :tags, :image, :body)
  end
end

rblog_html/rBlog/app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::ApplicationController
  def new
  end

  def create
  end
end

rblog_html/rBlog/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  def new
    @page_title = 'Add User'
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = 'User Created'
      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:notice] = 'User Updated'

      redirect_to admin_users_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    flash[:notice] = 'User Removed'

      redirect_to admin_users_path
  end

  def index
    if params[:search]
      @users = User.search(params[:search]).all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    else
      @users = User.all.order('created_at DESC').paginate(:per_page => 10, :page => params[:page])
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

rblog_html/rBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rblog_html/rBlog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  end
end

rblog_html/rBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
end

rblog_html/rBlog/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

rblog_html/rBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  	@categories = Category.all
  end

  def show
  end
end

rblog_html/rBlog/app/helpers/about_helper.rb
module AboutHelper
end

rblog_html/rBlog/app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

rblog_html/rBlog/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

rblog_html/rBlog/app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

rblog_html/rBlog/app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

rblog_html/rBlog/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

rblog_html/rBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

rblog_html/rBlog/app/helpers/categories_helper.rb
module CategoriesHelper
end

rblog_html/rBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

rblog_html/rBlog/app/helpers/contacts_helper.rb
module ContactsHelper
end

rblog_html/rBlog/app/helpers/posts_helper.rb
module PostsHelper
end

rblog_html/rBlog/app/views/admin/posts/edit.html.erb
<script>
  $(function() {
    $('textarea#edit').editable({
      inlineMode: false
    })
  });
</script>
<h2>Edit Post</h2>

<%= form_for [:admin, @post] do |f| %>
	<!-- Check for errors -->
	<% if @post.errors.any? %>
	    <% @post.errors.full_messages.each do |msg| %>
	    	<!-- Show errors -->
	      	<div class="alert alert-danger"><%= msg %></div>
	    <% end %>
  	<% end %>

	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title ,class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :category %>
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :author %>
		<%= f.select :user_id, User.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :image %>
		<%= f.file_field :image %>	
	</div>
	<% if @post.image.exists? %>
		<%= image_tag @post.image.url,width:'100%' %>
	<% end %>
	<br>

	<div class="form-group">
		<%= f.label :tags %>
		<%= f.text_area :tags ,class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :body %>
		<%= f.text_area :body ,class:'form-control',id: 'edit'  %>
	</div>
	<br>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", admin_posts_path, class:'btn btn-default' %>
<% end %>

rblog_html/rBlog/app/views/admin/posts/index.html.erb
<h2 class="page-header">Posts <%=link_to "Create New", new_admin_post_path, class:'btn btn-success pull-right' %></h2>
<% if @posts.exists? %>
  <table class="table table-striped">
    <tr>
      <th>Post Title</th>
      <th>Post Category</th>
      <th>Date Created</th>
      <th>Actions</th>
    </tr>
      <% @posts.each do |post| %>
      <tr>
            <td><%= post.title %></td>
            <td><%= post.category.name %></td>
            <td><%= post.created_at.to_time.strftime('%B %e at %l:%M %p') %>
            <td><%=link_to "Edit", edit_admin_post_path(post), class:'btn btn-primary' %> <%=link_to "Delete", admin_post_path(post), class:'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
  </table>
  <%= will_paginate @posts %>
<% else %>
    <p>There are no posts</p>
<% end %>

rblog_html/rBlog/app/views/admin/posts/new.html.erb
<script>
  $(function() {
    $('textarea#edit').editable({
      inlineMode: false
    })
  });
</script>
<h2>Add New Post</h2>

<%= form_for [:admin, @post] do |f| %>
	<!-- Check for errors -->
	<% if @post.errors.any? %>
	    <% @post.errors.full_messages.each do |msg| %>
	    	<!-- Show errors -->
	      	<div class="alert alert-danger"><%= msg %></div>
	    <% end %>
  	<% end %>

	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title ,class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :category %>
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :author %>
		<%= f.select :user_id, User.all.collect {|x| [x.name, x.id]}, {:include_blank => 'Select One'},class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :image %>
		<%= f.file_field :image %>	
	</div>
	<br>

	<div class="form-group">
		<%= f.label :tags %>
		<%= f.text_area :tags ,class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :body %>
		<%= f.text_area :body ,class:'form-control',id: 'edit'  %>
	</div>
	<br>
	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%=link_to "Cancel", admin_posts_path, class:'btn btn-default' %>
<% end %>

rblog_html/rBlog/app/views/posts/index.html.erb
<div id="posts-index">
  <% if @posts.exists? %>
    <% @posts.each_slice(2) do |post| %>
      <div class="row">
        <% post.each do |post| %>
          <div class="col-md-6">
              <div class="post">
                  <%= image_tag post.image.url,width:'100%' %>
                  <div class="post-content">
                    <h3><%= post.title %></h3>
                    <small>Posted by <%= post.user.name %> on <%= post.created_at.to_time.strftime('%B %e at %l:%M %p') %></small>
                    <%= raw post.body.truncate(200) %>
                    <%=link_to "Read More", post_path(post), class:'btn btn-primary' %>
                </div>
              </div>
           </div>
        <% end %>
      </div>
    <% end %>
  <% else %>
  <p>No posts yet</p>
  <% end %>
</div>