rblog_html/rBlog/config/routes.rb
Rails.application.routes.draw do
  get 'contact' => 'contacts#new'
  get 'contacts/create'
  get 'about' => 'about#index'
  namespace :admin do
    get 'sessions/new'
    get 'sessions/create'
  end
  namespace :admin do
    get 'users/new'
    get 'users/edit'
    get 'users/update'
    get 'users/show'
    get 'users/create'
    get 'users/index'
    get 'users/destroy'
  end
  namespace :admin do
    get 'comments/destroy'
  end
  get 'comments/new'
  namespace :admin do
    get 'categories/new'
    get 'categories/create'
    get 'categories/edit'
    get 'categories/update'
    get 'categories/destroy'
    get 'categories/index'
    get 'categories/show'
  end
  get 'categories/show'
  namespace :admin do
    get 'posts/new'
    get 'posts/create'
    get 'posts/edit'
    get 'posts/update'
    get 'posts/destroy'
    get 'posts/index'
    get 'posts/show'
  end
  get 'posts/index'
  get 'posts/show'

  resources :posts, :categories, :comments
  resources "contacts", only: [:new, :create]

  namespace :admin do
     resources :posts, :categories, :comments, :users
  end	  

  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rblog_html/rBlog/app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts

	validates :name, presence: true

	def self.search(query)
		where("name like ?", "%#{query}%")
	end
end

rblog_html/rBlog/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

rblog_html/rBlog/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :category
	belongs_to :user
	has_many :comments
	
	validates :title, presence: true
	validates :category_id, presence: true
	validates :body, presence: true

	has_attached_file :image, :default_url => ":style/rails1.jpg"
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.search(query)
		where("title like ? OR body like ?", "%#{query}%", "%#{query}%")
	end
end

rblog_html/rBlog/app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	before_save :encrypt_password

	has_many :posts

	validates :name, presence: true
	validates :email, presence: true
	validates :password, presence: true
	validates :password, confirmation: true

	def self.authenticate(email, password)
    	user = find_by_email(email)
	    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
	      user
	    else
	      nil
	    end
  	end
  
  	def encrypt_password
	    if password.present?
	      self.password_salt = BCrypt::Engine.generate_salt
	      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
	    end
  	end

  	def self.search(query)
		where("name like ? OR email like ?", "%#{query}%", "%#{query}%")
	end
end

rblog_html/rBlog/app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

rblog_html/rBlog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rblog_html/rBlog/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
  end
end

rblog_html/rBlog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  end
end

rblog_html/rBlog/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end

  def create
  end
end

rblog_html/rBlog/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  	@posts = Post.all
  	@categories = Category.all
  end

  def show
  end
end

rblog_html/rBlog/app/helpers/about_helper.rb
module AboutHelper
end

rblog_html/rBlog/app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

rblog_html/rBlog/app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

rblog_html/rBlog/app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
end

rblog_html/rBlog/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

rblog_html/rBlog/app/helpers/application_helper.rb
module ApplicationHelper
end

rblog_html/rBlog/app/helpers/categories_helper.rb
module CategoriesHelper
end

rblog_html/rBlog/app/helpers/comments_helper.rb
module CommentsHelper
end

rblog_html/rBlog/app/helpers/contacts_helper.rb
module ContactsHelper
end

rblog_html/rBlog/app/helpers/posts_helper.rb
module PostsHelper
end

rblog_html/rBlog/app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rblog_html/rBlog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rblog_html/rBlog/app/views/partials/_footer.html.erb
<footer>
      <p>Copyright &copy; 2014, rBlog | <a href="login.html">Admin Login</a></p>
</footer>

rblog_html/rBlog/app/views/partials/_sidebar.html.erb
<div class="list-group">
	<a href="#" class="list-group-item">News</a>
	<a href="#" class="list-group-item">Tutorials</a>
	<a href="#" class="list-group-item">Releases</a>
	<a href="#" class="list-group-item">Events</a>
</div>

rblog_html/rBlog/app/views/partials/admin/_search.html.erb
<% if params[:controller] == 'admin/posts' %>
<%= form_tag(admin_posts_path, :method => "get", id:"search-form", class:"search-form pull-right") do %>
	<div class="form-group">
  	<%= text_field_tag :search, params[:search], placeholder: "Search Posts", class:'form-control' %>
	</div>
	<%= submit_tag "Search", :name => nil, class:'btn btn-primary' %>
<% end %>
<% elsif params[:controller] == 'admin/categories' %>
	<%= form_tag(admin_categories_path, :method => "get", id:"search-form", class:"search-form pull-right") do %>
		<div class="form-group">
	  	<%= text_field_tag :search, params[:search], placeholder: "Search Categories", class:'form-control' %>
		</div>
		<%= submit_tag "Search", :name => nil, class:'btn btn-primary' %>
	<% end %>
<% elsif params[:controller] == 'admin/users' %>
	<%= form_tag(admin_users_path, :method => "get", id:"search-form", class:"search-form pull-right") do %>
			<div class="form-group">
	  		<%= text_field_tag :search, params[:search], placeholder: "Search Users", class:'form-control' %>
			</div>
			<%= submit_tag "Search", :name => nil, class:'btn btn-primary' %>
	<% end %>
<% end %>